#pragma config(Sensor, S2,     leftBumper,     sensorEV3_Touch)
#pragma config(Sensor, S3,     rightBumper,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#define NONE_PRESSED 0
#define BOTH_PRESSED 1
#define LEFT_PRESSED 2
#define RIGHT_PRESSED 3
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int pressed;
task motorController();
task sensorController();
void stop();
void pause(int ms);
void reverse(int ms);
void turnLeft(int ms);
void turnRight(int ms);

task main()
{
	startTask(motorController);
	startTask(sensorController);
	while(true)
	{
		sleep(50);
	}
}

task motorController()
{
	while (true)
	{
		switch(pressed) {
			case NONE_PRESSED:
				motor[leftMotor] = 30;
				motor[rightMotor] = 30;
				break;
			case BOTH_PRESSED:
				PlaySound(soundBeepBeep);
				reverse(1000);
				pause(2000);
				if (random(1)) {
					turnLeft(1000 + random(1000));
				} else {
					turnRight(1000 + random(1000);
				}
				break;
			case LEFT_PRESSED:
				reverse(1000);
				turnRight(500);
				break;
			case RIGHT_PRESSED:
				reverse(1000);
				turnLeft(500);
				break;

		}
		sleep(50);
		//motor[leftMotor] = 30;
		//motor[rightMotor] = 30;
	}

}

void stop() {
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

void pause(int ms) {
	stop();
	wait1Msec(ms);
}

void reverse(int ms) {
	motor[leftMotor] = -30;
	motor[rightMotor] = -30;
	wait1Msec(ms);
	stop();
}

void turnLeft(int ms) {
	motor[leftMotor] = -30;
	motor[rightMotor] = 30;
	wait1Msec(ms);
	stop();
}

void turnRight(int ms) {
	motor[rightMotor] = -30;
	motor[leftMotor] = 30;
	wait1Msec(ms);
	stop();
}

task sensorController()
{
	while (true)
	{
		if(SensorValue[leftBumper] && SensorValue[rightBumper]) {
			pressed = BOTH_PRESSED;
		}
		else if (SensorValue[leftBumper])
		{
			pressed = LEFT_PRESSED;
			//displayCenteredBigTextLine(4, "Left bumper pressed!");
			//setLEDColor(ledRed);
		}
		// If it's in a released state, turn the LED green
		else if (SensorValue[rightBumper])
		{
			pressed = RIGHT_PRESSED;
			//displayCenteredBigTextLine(4, "Right bumper pressed!");
			//setLEDColor(ledRed);
		}
		else
		{
			pressed = NONE_PRESSED;
			//displayCenteredBigTextLine(4, "No bumper pressed!");
			//setLEDColor(ledGreen);
		}
		sleep(50);
	}
}
